--------------------------------------------------------
-- Archivo creado  - lunes-mayo-19-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BUTACAS
--------------------------------------------------------

  CREATE TABLE "PROGRAMACION"."BUTACAS" 
   (	"ID_BUTACA" NUMBER, 
	"FILA" VARCHAR2(10 BYTE), 
	"COLUMNA" VARCHAR2(10 BYTE), 
	"TIPO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ESPECTACULOS
--------------------------------------------------------

  CREATE TABLE "PROGRAMACION"."ESPECTACULOS" 
   (	"ID_ESPECTACULO" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"FECHA" DATE, 
	"PRECIO_BASE" NUMBER(6,2), 
	"PRECIO_VIP" NUMBER(6,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESERVAS
--------------------------------------------------------

  CREATE TABLE "PROGRAMACION"."RESERVAS" 
   (	"ID_RESERVA" NUMBER, 
	"ID_ESPECTACULO" NUMBER, 
	"ID_BUTACA" NUMBER, 
	"ESTADO" VARCHAR2(20 BYTE), 
	"ID_USUARIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESERVAS_TEMP
--------------------------------------------------------

  CREATE TABLE "PROGRAMACION"."RESERVAS_TEMP" 
   (	"ID_RESERVA" NUMBER, 
	"ID_ESPECTACULO" NUMBER, 
	"ID_BUTACA" NUMBER, 
	"ESTADO" VARCHAR2(20 BYTE), 
	"ID_USUARIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "PROGRAMACION"."USUARIOS" 
   (	"ID_USUARIO" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"CONTRASEÑA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence SEQ_RESERVAS
--------------------------------------------------------

   CREATE SEQUENCE  "PROGRAMACION"."SEQ_RESERVAS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 70 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USUARIOS
--------------------------------------------------------

   CREATE SEQUENCE  "PROGRAMACION"."SEQ_USUARIOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE ;
REM INSERTING into PROGRAMACION.BUTACAS
SET DEFINE OFF;
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('1','1','1','VIP');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('2','1','2','VIP');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('3','1','3','VIP');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('4','1','4','VIP');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('5','1','5','VIP');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('6','1','6','VIP');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('7','2','1','ESTANDAR');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('8','2','2','ESTANDAR');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('9','2','3','ESTANDAR');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('10','2','4','ESTANDAR');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('11','2','5','ESTANDAR');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('12','2','6','ESTANDAR');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('13','3','1','ESTANDAR');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('14','3','2','ESTANDAR');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('15','3','3','ESTANDAR');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('16','3','4','ESTANDAR');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('17','3','5','ESTANDAR');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('18','3','6','ESTANDAR');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('19','4','1','ESTANDAR');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('20','4','2','ESTANDAR');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('21','4','3','ESTANDAR');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('22','4','4','ESTANDAR');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('23','4','5','ESTANDAR');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('24','4','6','ESTANDAR');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('25','5','1','ESTANDAR');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('26','5','2','ESTANDAR');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('27','5','3','ESTANDAR');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('28','5','4','ESTANDAR');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('29','5','5','ESTANDAR');
Insert into PROGRAMACION.BUTACAS (ID_BUTACA,FILA,COLUMNA,TIPO) values ('30','5','6','ESTANDAR');
REM INSERTING into PROGRAMACION.ESPECTACULOS
SET DEFINE OFF;
Insert into PROGRAMACION.ESPECTACULOS (ID_ESPECTACULO,NOMBRE,FECHA,PRECIO_BASE,PRECIO_VIP) values ('1','Cars',to_date('10/05/25','DD/MM/RR'),'10','15');
Insert into PROGRAMACION.ESPECTACULOS (ID_ESPECTACULO,NOMBRE,FECHA,PRECIO_BASE,PRECIO_VIP) values ('2','Dragon Ball Super',to_date('12/05/25','DD/MM/RR'),'12','18');
Insert into PROGRAMACION.ESPECTACULOS (ID_ESPECTACULO,NOMBRE,FECHA,PRECIO_BASE,PRECIO_VIP) values ('3','Spiderman',to_date('01/06/25','DD/MM/RR'),'14','20');
Insert into PROGRAMACION.ESPECTACULOS (ID_ESPECTACULO,NOMBRE,FECHA,PRECIO_BASE,PRECIO_VIP) values ('4','Frozen',to_date('05/06/25','DD/MM/RR'),'12','18');
REM INSERTING into PROGRAMACION.RESERVAS
SET DEFINE OFF;
Insert into PROGRAMACION.RESERVAS (ID_RESERVA,ID_ESPECTACULO,ID_BUTACA,ESTADO,ID_USUARIO) values ('50','2','9','CANCELADA','1');
Insert into PROGRAMACION.RESERVAS (ID_RESERVA,ID_ESPECTACULO,ID_BUTACA,ESTADO,ID_USUARIO) values ('51','2','15','CANCELADA','1');
Insert into PROGRAMACION.RESERVAS (ID_RESERVA,ID_ESPECTACULO,ID_BUTACA,ESTADO,ID_USUARIO) values ('52','2','16','CANCELADA','1');
Insert into PROGRAMACION.RESERVAS (ID_RESERVA,ID_ESPECTACULO,ID_BUTACA,ESTADO,ID_USUARIO) values ('53','2','10','CANCELADA','1');
Insert into PROGRAMACION.RESERVAS (ID_RESERVA,ID_ESPECTACULO,ID_BUTACA,ESTADO,ID_USUARIO) values ('54','2','15','CANCELADA','1');
Insert into PROGRAMACION.RESERVAS (ID_RESERVA,ID_ESPECTACULO,ID_BUTACA,ESTADO,ID_USUARIO) values ('55','2','9','CANCELADA','1');
Insert into PROGRAMACION.RESERVAS (ID_RESERVA,ID_ESPECTACULO,ID_BUTACA,ESTADO,ID_USUARIO) values ('56','2','10','CANCELADA','1');
Insert into PROGRAMACION.RESERVAS (ID_RESERVA,ID_ESPECTACULO,ID_BUTACA,ESTADO,ID_USUARIO) values ('57','2','16','CANCELADA','1');
Insert into PROGRAMACION.RESERVAS (ID_RESERVA,ID_ESPECTACULO,ID_BUTACA,ESTADO,ID_USUARIO) values ('58','2','16','CANCELADA','1');
Insert into PROGRAMACION.RESERVAS (ID_RESERVA,ID_ESPECTACULO,ID_BUTACA,ESTADO,ID_USUARIO) values ('59','2','10','CANCELADA','1');
Insert into PROGRAMACION.RESERVAS (ID_RESERVA,ID_ESPECTACULO,ID_BUTACA,ESTADO,ID_USUARIO) values ('60','2','9','CANCELADA','1');
Insert into PROGRAMACION.RESERVAS (ID_RESERVA,ID_ESPECTACULO,ID_BUTACA,ESTADO,ID_USUARIO) values ('61','2','15','CANCELADA','1');
Insert into PROGRAMACION.RESERVAS (ID_RESERVA,ID_ESPECTACULO,ID_BUTACA,ESTADO,ID_USUARIO) values ('62','4','22','CANCELADA','1');
Insert into PROGRAMACION.RESERVAS (ID_RESERVA,ID_ESPECTACULO,ID_BUTACA,ESTADO,ID_USUARIO) values ('63','4','23','CANCELADA','1');
Insert into PROGRAMACION.RESERVAS (ID_RESERVA,ID_ESPECTACULO,ID_BUTACA,ESTADO,ID_USUARIO) values ('64','4','17','CANCELADA','1');
Insert into PROGRAMACION.RESERVAS (ID_RESERVA,ID_ESPECTACULO,ID_BUTACA,ESTADO,ID_USUARIO) values ('47','2','21','CANCELADA','1');
Insert into PROGRAMACION.RESERVAS (ID_RESERVA,ID_ESPECTACULO,ID_BUTACA,ESTADO,ID_USUARIO) values ('48','2','22','CANCELADA','1');
Insert into PROGRAMACION.RESERVAS (ID_RESERVA,ID_ESPECTACULO,ID_BUTACA,ESTADO,ID_USUARIO) values ('49','2','16','CANCELADA','1');
Insert into PROGRAMACION.RESERVAS (ID_RESERVA,ID_ESPECTACULO,ID_BUTACA,ESTADO,ID_USUARIO) values ('65','4','16','CANCELADA','1');
Insert into PROGRAMACION.RESERVAS (ID_RESERVA,ID_ESPECTACULO,ID_BUTACA,ESTADO,ID_USUARIO) values ('66','1','23','CANCELADA','1');
Insert into PROGRAMACION.RESERVAS (ID_RESERVA,ID_ESPECTACULO,ID_BUTACA,ESTADO,ID_USUARIO) values ('67','1','29','CANCELADA','1');
Insert into PROGRAMACION.RESERVAS (ID_RESERVA,ID_ESPECTACULO,ID_BUTACA,ESTADO,ID_USUARIO) values ('68','1','30','CANCELADA','1');
Insert into PROGRAMACION.RESERVAS (ID_RESERVA,ID_ESPECTACULO,ID_BUTACA,ESTADO,ID_USUARIO) values ('69','1','24','CANCELADA','1');
REM INSERTING into PROGRAMACION.RESERVAS_TEMP
SET DEFINE OFF;
REM INSERTING into PROGRAMACION.USUARIOS
SET DEFINE OFF;
Insert into PROGRAMACION.USUARIOS (ID_USUARIO,NOMBRE,EMAIL,"CONTRASEÑA") values ('1','Adrián Castellano','acasra15@gmail.com','Acr22');
Insert into PROGRAMACION.USUARIOS (ID_USUARIO,NOMBRE,EMAIL,"CONTRASEÑA") values ('2','Ana García','anagarcia@gmail.com','Ana');
Insert into PROGRAMACION.USUARIOS (ID_USUARIO,NOMBRE,EMAIL,"CONTRASEÑA") values ('3','Fran','fran123@gmail.com','fran123');
Insert into PROGRAMACION.USUARIOS (ID_USUARIO,NOMBRE,EMAIL,"CONTRASEÑA") values ('4','Luis','Luis123@gmail.com','Luis123');
--------------------------------------------------------
--  DDL for Index UK_USUARIOS_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROGRAMACION"."UK_USUARIOS_EMAIL" ON "PROGRAMACION"."USUARIOS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger BIU_MAX_RESERVAS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROGRAMACION"."BIU_MAX_RESERVAS" 
BEFORE INSERT OR UPDATE ON PROGRAMACION.RESERVAS
FOR EACH ROW
DECLARE
    v_total_reservas NUMBER;
BEGIN
    -- Validar solo cuando se inserta o actualiza a estado 'RESERVADA'
    IF :NEW.estado = 'RESERVADA' THEN
        SELECT COUNT(*)
        INTO v_total_reservas
        FROM PROGRAMACION.RESERVAS
        WHERE id_usuario = :NEW.id_usuario
          AND estado = 'RESERVADA';

        -- Si ya tiene 4 o más, lanzar excepción
        IF v_total_reservas >= 4 THEN
            RAISE_APPLICATION_ERROR(-20001, 'El usuario ya tiene el máximo de reservas activas permitidas (4).');
        END IF;
    END IF;
END;

/
ALTER TRIGGER "PROGRAMACION"."BIU_MAX_RESERVAS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_BEFORE_INSERT_USUARIO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROGRAMACION"."TRG_BEFORE_INSERT_USUARIO" 
BEFORE INSERT ON USUARIOS
FOR EACH ROW
BEGIN
  IF :NEW.ID_USUARIO IS NULL THEN
    :NEW.ID_USUARIO := SEQ_USUARIOS.NEXTVAL;
  END IF;
END;

/
ALTER TRIGGER "PROGRAMACION"."TRG_BEFORE_INSERT_USUARIO" ENABLE;
--------------------------------------------------------
--  Constraints for Table BUTACAS
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."BUTACAS" ADD PRIMARY KEY ("ID_BUTACA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESERVAS
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."RESERVAS" ADD PRIMARY KEY ("ID_RESERVA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."USUARIOS" ADD CONSTRAINT "UK_USUARIOS_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROGRAMACION"."USUARIOS" ADD PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESERVAS_TEMP
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."RESERVAS_TEMP" ADD PRIMARY KEY ("ID_RESERVA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESPECTACULOS
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."ESPECTACULOS" ADD PRIMARY KEY ("ID_ESPECTACULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVAS
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."RESERVAS" ADD FOREIGN KEY ("ID_ESPECTACULO")
	  REFERENCES "PROGRAMACION"."ESPECTACULOS" ("ID_ESPECTACULO") ENABLE;
  ALTER TABLE "PROGRAMACION"."RESERVAS" ADD FOREIGN KEY ("ID_BUTACA")
	  REFERENCES "PROGRAMACION"."BUTACAS" ("ID_BUTACA") ENABLE;
  ALTER TABLE "PROGRAMACION"."RESERVAS" ADD FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "PROGRAMACION"."USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVAS_TEMP
--------------------------------------------------------

  ALTER TABLE "PROGRAMACION"."RESERVAS_TEMP" ADD FOREIGN KEY ("ID_ESPECTACULO")
	  REFERENCES "PROGRAMACION"."ESPECTACULOS" ("ID_ESPECTACULO") ENABLE;
  ALTER TABLE "PROGRAMACION"."RESERVAS_TEMP" ADD FOREIGN KEY ("ID_BUTACA")
	  REFERENCES "PROGRAMACION"."BUTACAS" ("ID_BUTACA") ENABLE;
  ALTER TABLE "PROGRAMACION"."RESERVAS_TEMP" ADD FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "PROGRAMACION"."USUARIOS" ("ID_USUARIO") ENABLE;
